# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ObjCTDD' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  # Pods for ObjCTDD

  target 'ObjCTDDTests' do
    inherit! :search_paths
    
    # Pods for testing
    pod "Kiwi"

  end

end
