# Uncomment the next line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!

target 'APIManagerKit' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for APIManagerKit
	pod 'Alamofire', '~> 4.0'
	pod 'SWXMLHash', '~> 3.0.0'

end

target 'CurrencyExchange' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CurrencyExchange

end
