# Uncomment this line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'

target 'WeatherApp' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WeatherApp    
  pod 'Alamofire', '~> 4.0'
  pod 'MBProgressHUD', '~> 1.0.0'

  target 'WeatherAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'WeatherAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
