# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'Employee-With-Firebase' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Employee-With-Firebase
  pod 'Firebase/Core'
  pod 'Firebase/AdMob'
  pod 'Firebase/Messaging'
  pod 'Firebase/Database'
  pod 'Firebase/Invites'
  pod 'Firebase/DynamicLinks'
  pod 'Firebase/Crash'
  pod 'Firebase/RemoteConfig'
  pod 'Firebase/Auth'
  pod 'Firebase/Storage'
  pod 'FirebaseUI'

end
